# Generated by Django 2.0 on 2017-12-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body_type', models.CharField(max_length=200)),
                ('lenses', models.CharField(max_length=200)),
                ('structure', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business', models.CharField(max_length=200)),
                ('reputation', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heresy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founder', models.CharField(max_length=200)),
                ('quirk', models.CharField(max_length=200)),
                ('major_heresy', models.CharField(max_length=200)),
                ('attitude_towards_orthodoxt', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=200)),
                ('quirk', models.CharField(max_length=200)),
                ('motivation', models.CharField(max_length=200)),
                ('problem', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('atmosphere', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=200)),
                ('biosphere', models.CharField(max_length=200)),
                ('population', models.CharField(max_length=200)),
                ('tech_level', models.CharField(max_length=200)),
                ('enemies', models.CharField(max_length=200)),
                ('friends', models.CharField(max_length=200)),
                ('complications', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=200)),
                ('things', models.CharField(max_length=200)),
                ('capital_and_government', models.TextField()),
                ('cultural_notes', models.TextField()),
                ('adventures_prepared', models.TextField()),
                ('party_activities_on_this_world', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('leadership', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
                ('outsiders', models.CharField(max_length=200)),
                ('issues', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalGroupI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ideology', models.CharField(max_length=200)),
                ('leadership', models.CharField(max_length=200)),
                ('key_issues', models.CharField(max_length=200)),
                ('relationships_towards_outsiders', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('leadership', models.CharField(max_length=200)),
                ('evolution', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nav_designation', models.CharField(max_length=50)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='heresy',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.Religion'),
        ),
    ]
