# Generated by Django 2.0 on 2017-12-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliticalGroupI',
        ),
        migrations.RenameField(
            model_name='politicalgroup',
            old_name='issues',
            new_name='key_issues',
        ),
    ]
