# Generated by Django 2.0 on 2017-12-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0003_auto_20171227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='complications',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='enemies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='friends',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='places',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='things',
            field=models.TextField(),
        ),
    ]
