# Generated by Django 2.0 on 2017-12-28 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0005_planet_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlienBodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlienLenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlienStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlienVarAvian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AlienVarExotic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AlienVarInsect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AlienVarMammal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AlienVarReptile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NPCAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NPCGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NPCHeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='NPCMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NPCProblems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NPCQuirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quirk', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickArchitecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickCorpBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickCorpName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('organization', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickCorpReputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuickHeresyAttitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.CharField(max_length=128)),
                ('adjective', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickHeresyFounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='QuickHeresyHeresy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heresy', models.TextField()),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickHeresyQuirk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quirk', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='QuickPoliticalIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('tag', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickPoliticalLeadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickPoliticalName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element1', models.CharField(max_length=32, unique=True)),
                ('element2', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuickPoliticalOutsiders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickPoliticalPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickReligionEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution', models.TextField()),
                ('adjective', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickReligionLeadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadership', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuickReligionOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('adjective', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuickRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldAtmosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBiosphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorldPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorldTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('enemies', models.TextField(blank=True)),
                ('friends', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('things', models.TextField(blank=True)),
                ('places', models.TextField(blank=True)),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorldTechLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorldTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField()),
                ('short', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='planet',
            name='atmosphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.WorldAtmosphere'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='biosphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.WorldBiosphere'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.WorldPopulation'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='tech_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.WorldTechLevel'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='temperature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.WorldTemperature'),
        ),
    ]
