# Generated by Django 2.0 on 2017-12-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0006_auto_20171228_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='enemies',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='places',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='things',
        ),
    ]
