# Generated by Django 2.0 on 2017-12-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0007_auto_20171229_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcquirk',
            name='quirk',
            field=models.CharField(max_length=64),
        ),
    ]
