# Generated by Django 2.0 on 2017-12-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0008_auto_20171229_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickarchitecture',
            name='element',
            field=models.CharField(max_length=64),
        ),
    ]
