# Generated by Django 2.0 on 2017-12-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0009_auto_20171229_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldtag',
            name='short',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
