# Generated by Django 2.0 on 2017-12-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0011_auto_20171229_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
