# Generated by Django 2.0 on 2017-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0012_auto_20171229_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='system_name_designation',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
