# Generated by Django 2.0 on 2017-12-29 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0013_auto_20171229_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alien',
            name='lenses',
        ),
        migrations.RemoveField(
            model_name='alien',
            name='structure',
        ),
        migrations.AddField(
            model_name='alien',
            name='lenses1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swn.AlienLenses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alien',
            name='lenses2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swn.AlienLenses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alien',
            name='structure1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='swn.AlienStructure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alien',
            name='structure2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swn.AlienStructure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alien',
            name='body_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.AlienBodyType'),
        ),
        migrations.AlterField(
            model_name='alien',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
