# Generated by Django 2.0 on 2017-12-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0014_auto_20171229_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alien',
            name='structure2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='swn.AlienStructure'),
        ),
    ]
