# Generated by Django 2.0 on 2017-12-29 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0016_auto_20171229_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quickheresyheresy',
            old_name='heresy',
            new_name='major_heresy',
        ),
        migrations.AlterField(
            model_name='company',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickCorpBusiness'),
        ),
        migrations.AlterField(
            model_name='company',
            name='reputation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickCorpReputation'),
        ),
        migrations.AlterField(
            model_name='heresy',
            name='attitude_towards_orthodoxt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickHeresyAttitude'),
        ),
        migrations.AlterField(
            model_name='heresy',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickHeresyFounder'),
        ),
        migrations.AlterField(
            model_name='heresy',
            name='major_heresy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickHeresyHeresy'),
        ),
        migrations.AlterField(
            model_name='heresy',
            name='quirk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickHeresyQuirk'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCAge'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCGender'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='height',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCHeight'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='motivation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCMotivation'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCProblems'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='quirk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.NPCQuirk'),
        ),
        migrations.AlterField(
            model_name='politicalgroup',
            name='key_issues',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickPoliticalIssues'),
        ),
        migrations.AlterField(
            model_name='politicalgroup',
            name='leadership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickPoliticalLeadership'),
        ),
        migrations.AlterField(
            model_name='politicalgroup',
            name='outsiders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickPoliticalOutsiders'),
        ),
        migrations.AlterField(
            model_name='politicalgroup',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickPoliticalPolicy'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='evolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickReligionEvolution'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='leadership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickReligionLeadership'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swn.QuickReligionOrigin'),
        ),
    ]
