# Generated by Django 2.0 on 2018-01-09 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0020_auto_20180109_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faction_Assets',
            new_name='Faction_Asset',
        ),
    ]
