# Generated by Django 2.0 on 2018-01-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0022_auto_20180109_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faction',
            name='pc_reputation',
            field=models.CharField(default='Neutral', max_length=32),
        ),
    ]
