# Generated by Django 2.0 on 2018-01-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0023_auto_20180109_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction_asset',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
