# Generated by Django 2.0 on 2018-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0027_remove_faction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
