# Generated by Django 2.0 on 2018-02-16 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swn', '0031_auto_20180209_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='last_editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
