# Generated by Django 2.0 on 2018-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swn', '0033_auto_20180216_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='alien',
            name='alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
