INSERT INTO "swn_alienvarinsect" VALUES (1, 'Sucking mouthparts');
INSERT INTO "swn_alienvarinsect" VALUES (2, 'Chewing mouthparts');
INSERT INTO "swn_alienvarinsect" VALUES (3, 'Jewel-colored chitin');
INSERT INTO "swn_alienvarinsect" VALUES (4, '$$2D4 pairs of limbs');
INSERT INTO "swn_alienvarinsect" VALUES (5, 'Membranous wings');
INSERT INTO "swn_alienvarinsect" VALUES (6, 'Deposits eggs in live prey');
INSERT INTO "swn_alienvarinsect" VALUES (7, 'Has "silk" spinnerets');
INSERT INTO "swn_alienvarinsect" VALUES (8, 'Has a chrysalis life stage');
INSERT INTO "swn_alienvarinsect" VALUES (9, 'No mouth; adult form lives only to reproduce');
INSERT INTO "swn_alienvarinsect" VALUES (10, '$$1D4 pairs of eyes or eyespots');
INSERT INTO "swn_alienvarinsect" VALUES (11, 'Sluglike body');
INSERT INTO "swn_alienvarinsect" VALUES (12, 'Color-changing exoskeleton');
INSERT INTO "swn_alienvarinsect" VALUES (13, 'Always encountered in groups');
INSERT INTO "swn_alienvarinsect" VALUES (14, 'Hums or buzzes in intricate patterns');
INSERT INTO "swn_alienvarinsect" VALUES (15, 'Lives in hives led by a queen');
INSERT INTO "swn_alienvarinsect" VALUES (16, 'Killing one causes others nearby to go berserk');
INSERT INTO "swn_alienvarinsect" VALUES (17, 'Emits powerful pheromones');
INSERT INTO "swn_alienvarinsect" VALUES (18, 'Hides itself to ambush prey');
INSERT INTO "swn_alienvarinsect" VALUES (19, 'Prefers subterranean environments');
INSERT INTO "swn_alienvarinsect" VALUES (20, 'Emits noxious or poisonous stench when killed');
