INSERT INTO "swn_alienvarexotic" VALUES (1, 'Rocklike body');
INSERT INTO "swn_alienvarexotic" VALUES (2, '$$1D4 pairs of eyestalks');
INSERT INTO "swn_alienvarexotic" VALUES (3, 'Rolls on wheels');
INSERT INTO "swn_alienvarexotic" VALUES (4, 'Chainsaw-like mouthparts or claws');
INSERT INTO "swn_alienvarexotic" VALUES (5, 'Metallic hide');
INSERT INTO "swn_alienvarexotic" VALUES (6, 'Natural laser emitters');
INSERT INTO "swn_alienvarexotic" VALUES (7, 'Launches chemically-powered darts');
INSERT INTO "swn_alienvarexotic" VALUES (8, 'Amoeba-like body');
INSERT INTO "swn_alienvarexotic" VALUES (9, 'Crystalline tissues');
INSERT INTO "swn_alienvarexotic" VALUES (10, 'Gas-sack body');
INSERT INTO "swn_alienvarexotic" VALUES (11, '$$2D10 tentacles');
INSERT INTO "swn_alienvarexotic" VALUES (12, 'Gelatinous liquid body');
INSERT INTO "swn_alienvarexotic" VALUES (13, 'Radioactive flesh');
INSERT INTO "swn_alienvarexotic" VALUES (14, 'Uses sonic attacks to stun prey');
INSERT INTO "swn_alienvarexotic" VALUES (15, 'Colony entity made up of numerous small animals');
INSERT INTO "swn_alienvarexotic" VALUES (16, 'Controlled by neural symbiont');
INSERT INTO "swn_alienvarexotic" VALUES (17, 'Absorbs electromagnetic energy');
INSERT INTO "swn_alienvarexotic" VALUES (18, 'Precious mineral carapace or exoskeleton');
INSERT INTO "swn_alienvarexotic" VALUES (19, 'Double damage from a particular type of injury');
INSERT INTO "swn_alienvarexotic" VALUES (20, 'Mobile plant life');
