INSERT INTO "swn_alienvaravian" VALUES (1, 'Sharp feathers');
INSERT INTO "swn_alienvaravian" VALUES (2, '$$1D3 pairs of wings');
INSERT INTO "swn_alienvaravian" VALUES (3, 'Long, sinuous neck');
INSERT INTO "swn_alienvaravian" VALUES (4, 'Brilliant coloration');
INSERT INTO "swn_alienvaravian" VALUES (5, 'Membranous wings');
INSERT INTO "swn_alienvaravian" VALUES (6, 'Can hover');
INSERT INTO "swn_alienvaravian" VALUES (7, 'Beautiful song');
INSERT INTO "swn_alienvaravian" VALUES (8, 'Flightless');
INSERT INTO "swn_alienvaravian" VALUES (9, 'Fights prey on the ground');
INSERT INTO "swn_alienvaravian" VALUES (10, 'Launches secretions at prey');
INSERT INTO "swn_alienvaravian" VALUES (11, 'Lifts and drops prey');
INSERT INTO "swn_alienvaravian" VALUES (12, 'Exhales flame or other toxic substance');
INSERT INTO "swn_alienvaravian" VALUES (13, 'Always appears in groups');
INSERT INTO "swn_alienvaravian" VALUES (14, 'Long prehensile tail');
INSERT INTO "swn_alienvaravian" VALUES (15, 'Animal is cold-blooded');
INSERT INTO "swn_alienvaravian" VALUES (16, 'Fur instead of feathers');
INSERT INTO "swn_alienvaravian" VALUES (17, 'Scales instead of feathers');
INSERT INTO "swn_alienvaravian" VALUES (18, 'Toothed beak');
INSERT INTO "swn_alienvaravian" VALUES (19, 'Has valuable or delicious eggs');
INSERT INTO "swn_alienvaravian" VALUES (20, 'Flies by means of lighter-than-air gas');
