INSERT INTO "swn_alienvarmammal" VALUES (1, 'Multiple mouths');
INSERT INTO "swn_alienvarmammal" VALUES (2, 'Quill-like fur');
INSERT INTO "swn_alienvarmammal" VALUES (3, 'Prehensile tail');
INSERT INTO "swn_alienvarmammal" VALUES (4, 'Eyes or eyespots on body');
INSERT INTO "swn_alienvarmammal" VALUES (5, 'Membranous wings');
INSERT INTO "swn_alienvarmammal" VALUES (6, 'Stench glands');
INSERT INTO "swn_alienvarmammal" VALUES (7, 'Peculiar vocalization');
INSERT INTO "swn_alienvarmammal" VALUES (8, 'Marsupial pouch');
INSERT INTO "swn_alienvarmammal" VALUES (9, 'Patterned fur or hide');
INSERT INTO "swn_alienvarmammal" VALUES (10, 'Expands or inflates when threatened');
INSERT INTO "swn_alienvarmammal" VALUES (11, 'Strictly nocturnal');
INSERT INTO "swn_alienvarmammal" VALUES (12, '$$1D6P1 limbs, including any tail');
INSERT INTO "swn_alienvarmammal" VALUES (13, 'Mottled or mangy fur');
INSERT INTO "swn_alienvarmammal" VALUES (14, 'Fires darts or quills');
INSERT INTO "swn_alienvarmammal" VALUES (15, 'Animal is cold-blooded');
INSERT INTO "swn_alienvarmammal" VALUES (16, 'Horns or body spikes');
INSERT INTO "swn_alienvarmammal" VALUES (17, 'Superb scent tracker');
INSERT INTO "swn_alienvarmammal" VALUES (18, 'Burrowing creature');
INSERT INTO "swn_alienvarmammal" VALUES (19, 'Creature lacks a sense- hearing, sight, or smell');
INSERT INTO "swn_alienvarmammal" VALUES (20, 'Creature is abnormally clever for an animal');
