INSERT INTO "swn_alienvarreptile" VALUES (1, 'Sharp-edged scales');
INSERT INTO "swn_alienvarreptile" VALUES (2, '$$1D4 pairs of eyes');
INSERT INTO "swn_alienvarreptile" VALUES (3, 'Extremely long tail');
INSERT INTO "swn_alienvarreptile" VALUES (4, 'Bellowing vocalization');
INSERT INTO "swn_alienvarreptile" VALUES (5, 'Burrowing foreclaws');
INSERT INTO "swn_alienvarreptile" VALUES (6, 'Hide is damp and slimy');
INSERT INTO "swn_alienvarreptile" VALUES (7, 'Eyeless');
INSERT INTO "swn_alienvarreptile" VALUES (8, 'Strong swimmer');
INSERT INTO "swn_alienvarreptile" VALUES (9, 'Spits venom');
INSERT INTO "swn_alienvarreptile" VALUES (10, 'Lies in ambush in bodies of water');
INSERT INTO "swn_alienvarreptile" VALUES (11, 'Brilliantly-hued scales or hide');
INSERT INTO "swn_alienvarreptile" VALUES (12, 'Horns or body spikes');
INSERT INTO "swn_alienvarreptile" VALUES (13, 'Large membranous frills');
INSERT INTO "swn_alienvarreptile" VALUES (14, 'Hibernates in caves and undisturbed nooks');
INSERT INTO "swn_alienvarreptile" VALUES (15, 'Glowing body parts');
INSERT INTO "swn_alienvarreptile" VALUES (16, 'Body is patterned with both scales and hide');
INSERT INTO "swn_alienvarreptile" VALUES (17, 'Springs on prey from elevated places');
INSERT INTO "swn_alienvarreptile" VALUES (18, 'Warm-blooded');
INSERT INTO "swn_alienvarreptile" VALUES (19, 'Furred');
INSERT INTO "swn_alienvarreptile" VALUES (20, 'Limbless body');
