INSERT INTO "swn_npcquirk" VALUES (1, 'Bald');
INSERT INTO "swn_npcquirk" VALUES (2, 'Terrible taste in clothing');
INSERT INTO "swn_npcquirk" VALUES (3, 'Very thin');
INSERT INTO "swn_npcquirk" VALUES (4, 'Powerful build');
INSERT INTO "swn_npcquirk" VALUES (5, 'Bad eyesight, wears spectacles');
INSERT INTO "swn_npcquirk" VALUES (6, 'Carries work tools constantly');
INSERT INTO "swn_npcquirk" VALUES (7, 'Long hair');
INSERT INTO "swn_npcquirk" VALUES (8, 'male:Bearded,female:Ankle-length hair');
INSERT INTO "swn_npcquirk" VALUES (9, 'Scars all over hands');
INSERT INTO "swn_npcquirk" VALUES (10, 'Missing digits or an ear');
INSERT INTO "swn_npcquirk" VALUES (11, 'Smells like their work');
INSERT INTO "swn_npcquirk" VALUES (12, 'Repeats themself constantly');
INSERT INTO "swn_npcquirk" VALUES (13, 'Talks about tabloid articles');
INSERT INTO "swn_npcquirk" VALUES (14, 'Booming voice');
INSERT INTO "swn_npcquirk" VALUES (15, 'Vocal dislike of offworlders');
INSERT INTO "swn_npcquirk" VALUES (16, 'Always snuffling');
INSERT INTO "swn_npcquirk" VALUES (17, 'Missing teeth');
INSERT INTO "swn_npcquirk" VALUES (18, 'Fastidiously neat');
INSERT INTO "swn_npcquirk" VALUES (19, 'Wears religious emblems');
INSERT INTO "swn_npcquirk" VALUES (20, 'Speaks as little as possible');
