INSERT INTO "swn_quickheresyquirk" VALUES (1, 'Clergy of only one gender.');
INSERT INTO "swn_quickheresyquirk" VALUES (2, 'Dietary prohibitions.');
INSERT INTO "swn_quickheresyquirk" VALUES (3, 'Characteristic item of clothing or jewelry.');
INSERT INTO "swn_quickheresyquirk" VALUES (4, 'Public prayer at set times or places.');
INSERT INTO "swn_quickheresyquirk" VALUES (5, 'Forbidden to do something commonly done.');
INSERT INTO "swn_quickheresyquirk" VALUES (6, 'Anti-intellectual, deploring secular learning');
INSERT INTO "swn_quickheresyquirk" VALUES (7, 'Mystical, seeking union with God through meditation.');
INSERT INTO "swn_quickheresyquirk" VALUES (8, 'Lives in visibly distinct houses or districts.');
INSERT INTO "swn_quickheresyquirk" VALUES (9, 'Has a language specific to the sect.');
INSERT INTO "swn_quickheresyquirk" VALUES (10, 'Greatly respects learning and education.');
INSERT INTO "swn_quickheresyquirk" VALUES (11, 'Favors specific colors or symbols.');
INSERT INTO "swn_quickheresyquirk" VALUES (12, 'Has unique purification rituals.');
INSERT INTO "swn_quickheresyquirk" VALUES (13, 'Always armed.');
INSERT INTO "swn_quickheresyquirk" VALUES (14, 'Forbids marriage or romance outside the sect.');
INSERT INTO "swn_quickheresyquirk" VALUES (15, 'Will not eat with people outside the sect.');
INSERT INTO "swn_quickheresyquirk" VALUES (16, 'Must donate labor or tithe money to the sect.');
INSERT INTO "swn_quickheresyquirk" VALUES (17, 'Special friendliness toward another faith or ethnicity.');
INSERT INTO "swn_quickheresyquirk" VALUES (18, 'Favors certain professions for their membership.');
INSERT INTO "swn_quickheresyquirk" VALUES (19, 'Vigorous charity work among unbelievers.');
INSERT INTO "swn_quickheresyquirk" VALUES (20, 'Forbidden the use of certain technology.');
