INSERT INTO "swn_quickcorpbusiness" VALUES (1, 'Aeronautics');
INSERT INTO "swn_quickcorpbusiness" VALUES (2, 'Aeronautics');
INSERT INTO "swn_quickcorpbusiness" VALUES (3, 'Agriculture');
INSERT INTO "swn_quickcorpbusiness" VALUES (4, 'Agriculture');
INSERT INTO "swn_quickcorpbusiness" VALUES (5, 'Art');
INSERT INTO "swn_quickcorpbusiness" VALUES (6, 'Art');
INSERT INTO "swn_quickcorpbusiness" VALUES (7, 'Assassination');
INSERT INTO "swn_quickcorpbusiness" VALUES (8, 'Assassination');
INSERT INTO "swn_quickcorpbusiness" VALUES (9, 'Asteroid Mining');
INSERT INTO "swn_quickcorpbusiness" VALUES (10, 'Asteroid Mining');
INSERT INTO "swn_quickcorpbusiness" VALUES (11, 'Astrotech');
INSERT INTO "swn_quickcorpbusiness" VALUES (12, 'Astrotech');
INSERT INTO "swn_quickcorpbusiness" VALUES (13, 'Biotech');
INSERT INTO "swn_quickcorpbusiness" VALUES (14, 'Biotech');
INSERT INTO "swn_quickcorpbusiness" VALUES (15, 'Bootlegging');
INSERT INTO "swn_quickcorpbusiness" VALUES (16, 'Bootlegging');
INSERT INTO "swn_quickcorpbusiness" VALUES (17, 'Computer Hardware');
INSERT INTO "swn_quickcorpbusiness" VALUES (18, 'Computer Hardware');
INSERT INTO "swn_quickcorpbusiness" VALUES (19, 'Construction');
INSERT INTO "swn_quickcorpbusiness" VALUES (20, 'Construction');
INSERT INTO "swn_quickcorpbusiness" VALUES (21, 'Cybernetics');
INSERT INTO "swn_quickcorpbusiness" VALUES (22, 'Cybernetics');
INSERT INTO "swn_quickcorpbusiness" VALUES (23, 'Electronics');
INSERT INTO "swn_quickcorpbusiness" VALUES (24, 'Electronics');
INSERT INTO "swn_quickcorpbusiness" VALUES (25, 'Energy Weapons');
INSERT INTO "swn_quickcorpbusiness" VALUES (26, 'Energy Weapons');
INSERT INTO "swn_quickcorpbusiness" VALUES (27, 'Entertainment');
INSERT INTO "swn_quickcorpbusiness" VALUES (28, 'Entertainment');
INSERT INTO "swn_quickcorpbusiness" VALUES (29, 'Espionage');
INSERT INTO "swn_quickcorpbusiness" VALUES (30, 'Espionage');
INSERT INTO "swn_quickcorpbusiness" VALUES (31, 'Exploration');
INSERT INTO "swn_quickcorpbusiness" VALUES (32, 'Exploration');
INSERT INTO "swn_quickcorpbusiness" VALUES (33, 'Fishing');
INSERT INTO "swn_quickcorpbusiness" VALUES (34, 'Fishing');
INSERT INTO "swn_quickcorpbusiness" VALUES (35, 'Fuel Refining');
INSERT INTO "swn_quickcorpbusiness" VALUES (36, 'Fuel Refining');
INSERT INTO "swn_quickcorpbusiness" VALUES (37, 'Gambling');
INSERT INTO "swn_quickcorpbusiness" VALUES (38, 'Gambling');
INSERT INTO "swn_quickcorpbusiness" VALUES (39, 'Gemstones');
INSERT INTO "swn_quickcorpbusiness" VALUES (40, 'Gemstones');
INSERT INTO "swn_quickcorpbusiness" VALUES (41, 'Gengineering');
INSERT INTO "swn_quickcorpbusiness" VALUES (42, 'Gengineering');
INSERT INTO "swn_quickcorpbusiness" VALUES (43, 'Grav Vehicles');
INSERT INTO "swn_quickcorpbusiness" VALUES (44, 'Grav Vehicles');
INSERT INTO "swn_quickcorpbusiness" VALUES (45, 'Heavy Weapons');
INSERT INTO "swn_quickcorpbusiness" VALUES (46, 'Heavy Weapons');
INSERT INTO "swn_quickcorpbusiness" VALUES (47, 'Ideology');
INSERT INTO "swn_quickcorpbusiness" VALUES (48, 'Ideology');
INSERT INTO "swn_quickcorpbusiness" VALUES (49, 'Illicit Drugs');
INSERT INTO "swn_quickcorpbusiness" VALUES (50, 'Illicit Drugs');
INSERT INTO "swn_quickcorpbusiness" VALUES (51, 'Journalism');
INSERT INTO "swn_quickcorpbusiness" VALUES (52, 'Journalism');
INSERT INTO "swn_quickcorpbusiness" VALUES (53, 'Law Enforcement');
INSERT INTO "swn_quickcorpbusiness" VALUES (54, 'Law Enforcement');
INSERT INTO "swn_quickcorpbusiness" VALUES (55, 'Liquor');
INSERT INTO "swn_quickcorpbusiness" VALUES (56, 'Liquor');
INSERT INTO "swn_quickcorpbusiness" VALUES (57, 'Livestock');
INSERT INTO "swn_quickcorpbusiness" VALUES (58, 'Livestock');
INSERT INTO "swn_quickcorpbusiness" VALUES (59, 'Maltech');
INSERT INTO "swn_quickcorpbusiness" VALUES (60, 'Maltech');
INSERT INTO "swn_quickcorpbusiness" VALUES (61, 'Mercenary Work');
INSERT INTO "swn_quickcorpbusiness" VALUES (62, 'Mercenary Work');
INSERT INTO "swn_quickcorpbusiness" VALUES (63, 'Metallurgy');
INSERT INTO "swn_quickcorpbusiness" VALUES (64, 'Metallurgy');
INSERT INTO "swn_quickcorpbusiness" VALUES (65, 'Pharmaceuticals');
INSERT INTO "swn_quickcorpbusiness" VALUES (66, 'Pharmaceuticals');
INSERT INTO "swn_quickcorpbusiness" VALUES (67, 'Piracy');
INSERT INTO "swn_quickcorpbusiness" VALUES (68, 'Piracy');
INSERT INTO "swn_quickcorpbusiness" VALUES (69, 'Planetary Mining');
INSERT INTO "swn_quickcorpbusiness" VALUES (70, 'Planetary Mining');
INSERT INTO "swn_quickcorpbusiness" VALUES (71, 'Plastics');
INSERT INTO "swn_quickcorpbusiness" VALUES (72, 'Plastics');
INSERT INTO "swn_quickcorpbusiness" VALUES (73, 'Pretech');
INSERT INTO "swn_quickcorpbusiness" VALUES (74, 'Pretech');
INSERT INTO "swn_quickcorpbusiness" VALUES (75, 'Prisons');
INSERT INTO "swn_quickcorpbusiness" VALUES (76, 'Prisons');
INSERT INTO "swn_quickcorpbusiness" VALUES (77, 'Programming');
INSERT INTO "swn_quickcorpbusiness" VALUES (78, 'Programming');
INSERT INTO "swn_quickcorpbusiness" VALUES (79, 'Projectile Guns');
INSERT INTO "swn_quickcorpbusiness" VALUES (80, 'Projectile Guns');
INSERT INTO "swn_quickcorpbusiness" VALUES (81, 'Prostitution');
INSERT INTO "swn_quickcorpbusiness" VALUES (82, 'Prostitution');
INSERT INTO "swn_quickcorpbusiness" VALUES (83, 'Psionics');
INSERT INTO "swn_quickcorpbusiness" VALUES (84, 'Psionics');
INSERT INTO "swn_quickcorpbusiness" VALUES (85, 'Psitech');
INSERT INTO "swn_quickcorpbusiness" VALUES (86, 'Psitech');
INSERT INTO "swn_quickcorpbusiness" VALUES (87, 'Robotics');
INSERT INTO "swn_quickcorpbusiness" VALUES (88, 'Robotics');
INSERT INTO "swn_quickcorpbusiness" VALUES (89, 'Security');
INSERT INTO "swn_quickcorpbusiness" VALUES (90, 'Security');
INSERT INTO "swn_quickcorpbusiness" VALUES (91, 'Shipyards');
INSERT INTO "swn_quickcorpbusiness" VALUES (92, 'Shipyards');
INSERT INTO "swn_quickcorpbusiness" VALUES (93, 'Snacks');
INSERT INTO "swn_quickcorpbusiness" VALUES (94, 'Snacks');
INSERT INTO "swn_quickcorpbusiness" VALUES (95, 'Telcoms');
INSERT INTO "swn_quickcorpbusiness" VALUES (96, 'Telcoms');
INSERT INTO "swn_quickcorpbusiness" VALUES (97, 'Transport');
INSERT INTO "swn_quickcorpbusiness" VALUES (98, 'Transport');
INSERT INTO "swn_quickcorpbusiness" VALUES (99, 'Xenotech');
INSERT INTO "swn_quickcorpbusiness" VALUES (100, 'Xenotech');
