INSERT INTO "swn_quickcorpname" VALUES (1, 'Ad Astra', 'Alliance');
INSERT INTO "swn_quickcorpname" VALUES (2, 'Colonial', 'Association');
INSERT INTO "swn_quickcorpname" VALUES (3, 'Compass', 'Band');
INSERT INTO "swn_quickcorpname" VALUES (4, 'Daybreak', 'Circle');
INSERT INTO "swn_quickcorpname" VALUES (5, 'Frontier', 'Clan');
INSERT INTO "swn_quickcorpname" VALUES (6, 'Guo Yin', 'Combine');
INSERT INTO "swn_quickcorpname" VALUES (7, 'Highbeam', 'Company');
INSERT INTO "swn_quickcorpname" VALUES (8, 'Imani', 'Cooperative');
INSERT INTO "swn_quickcorpname" VALUES (9, 'Magnus', 'Corporation');
INSERT INTO "swn_quickcorpname" VALUES (10, 'Meteor', 'Enterprises');
INSERT INTO "swn_quickcorpname" VALUES (11, 'Neogen', 'Faction');
INSERT INTO "swn_quickcorpname" VALUES (12, 'New Dawn', 'Group');
INSERT INTO "swn_quickcorpname" VALUES (13, 'Omnitech', 'Megacorp');
INSERT INTO "swn_quickcorpname" VALUES (14, 'Outertech', 'Multistellar');
INSERT INTO "swn_quickcorpname" VALUES (15, 'Overwatch', 'Organization');
INSERT INTO "swn_quickcorpname" VALUES (16, 'Panstellar', 'Outift');
INSERT INTO "swn_quickcorpname" VALUES (17, 'Shogun', 'Pact');
INSERT INTO "swn_quickcorpname" VALUES (18, 'Silverlight', 'Partnership');
INSERT INTO "swn_quickcorpname" VALUES (19, 'Spiker', 'Ring');
INSERT INTO "swn_quickcorpname" VALUES (20, 'Stella', 'Society');
INSERT INTO "swn_quickcorpname" VALUES (21, 'Striker', 'Sodality');
INSERT INTO "swn_quickcorpname" VALUES (22, 'Sunbeam', 'Syndicate');
INSERT INTO "swn_quickcorpname" VALUES (23, 'Terra Prime', 'Union');
INSERT INTO "swn_quickcorpname" VALUES (24, 'Wayfarer', 'Unity');
INSERT INTO "swn_quickcorpname" VALUES (25, 'West Wind', 'Zaibatsu');
