INSERT INTO "swn_quickarchitecture" VALUES (101, 'Sharply pointed towers');
INSERT INTO "swn_quickarchitecture" VALUES (102, 'Squat towers');
INSERT INTO "swn_quickarchitecture" VALUES (103, 'Square, hexagonal, or oval towers');
INSERT INTO "swn_quickarchitecture" VALUES (104, 'Multi-branching towers');
INSERT INTO "swn_quickarchitecture" VALUES (105, 'Inverted towers, stretching underground');
INSERT INTO "swn_quickarchitecture" VALUES (106, 'Bulbous towers');
INSERT INTO "swn_quickarchitecture" VALUES (107, 'Flat-topped towers');
INSERT INTO "swn_quickarchitecture" VALUES (108, 'Multiple towers that merge into one');
INSERT INTO "swn_quickarchitecture" VALUES (109, 'Skeletal towers');
INSERT INTO "swn_quickarchitecture" VALUES (110, 'Twisted towers');
INSERT INTO "swn_quickarchitecture" VALUES (201, 'Square foundations');
INSERT INTO "swn_quickarchitecture" VALUES (202, 'Hexagonal foundations');
INSERT INTO "swn_quickarchitecture" VALUES (203, 'Circular foundations');
INSERT INTO "swn_quickarchitecture" VALUES (204, 'Raised foundations');
INSERT INTO "swn_quickarchitecture" VALUES (205, 'Pillared foundations');
INSERT INTO "swn_quickarchitecture" VALUES (206, 'Sloped foundations');
INSERT INTO "swn_quickarchitecture" VALUES (207, 'Entrenched foundations');
INSERT INTO "swn_quickarchitecture" VALUES (208, 'Elongated rectangular foundations');
INSERT INTO "swn_quickarchitecture" VALUES (209, 'Triangular foundations');
INSERT INTO "swn_quickarchitecture" VALUES (210, 'Oval foundations');
INSERT INTO "swn_quickarchitecture" VALUES (301, 'Bas-reliefs on walls');
INSERT INTO "swn_quickarchitecture" VALUES (302, 'Painting on walls');
INSERT INTO "swn_quickarchitecture" VALUES (303, 'Mosaics on walls or floors');
INSERT INTO "swn_quickarchitecture" VALUES (304, 'Statues inset in wall niches');
INSERT INTO "swn_quickarchitecture" VALUES (305, 'Tiling on surfaces');
INSERT INTO "swn_quickarchitecture" VALUES (306, 'Carvings on walls');
INSERT INTO "swn_quickarchitecture" VALUES (307, 'Moldings on walls');
INSERT INTO "swn_quickarchitecture" VALUES (308, 'Paneling on walls');
INSERT INTO "swn_quickarchitecture" VALUES (309, 'Geometric designs on surfaces');
INSERT INTO "swn_quickarchitecture" VALUES (310, 'Featureless surfaces');
INSERT INTO "swn_quickarchitecture" VALUES (401, 'Flying buttresses');
INSERT INTO "swn_quickarchitecture" VALUES (402, 'Smooth pillars');
INSERT INTO "swn_quickarchitecture" VALUES (403, 'Adorned pillars');
INSERT INTO "swn_quickarchitecture" VALUES (404, 'Raised embankments');
INSERT INTO "swn_quickarchitecture" VALUES (405, 'Pier buttresses');
INSERT INTO "swn_quickarchitecture" VALUES (406, 'Scroll buttresses');
INSERT INTO "swn_quickarchitecture" VALUES (407, 'False, decorative buttresses');
INSERT INTO "swn_quickarchitecture" VALUES (408, 'Pyramidal support piers');
INSERT INTO "swn_quickarchitecture" VALUES (409, 'Squared support piers');
INSERT INTO "swn_quickarchitecture" VALUES (410, 'Seeming lack of supports or buttresses');
INSERT INTO "swn_quickarchitecture" VALUES (501, 'Round arches');
INSERT INTO "swn_quickarchitecture" VALUES (502, 'Lancet arches');
INSERT INTO "swn_quickarchitecture" VALUES (503, 'Oriental arches');
INSERT INTO "swn_quickarchitecture" VALUES (504, 'Horseshoe arches');
INSERT INTO "swn_quickarchitecture" VALUES (505, 'Multifoil arches');
INSERT INTO "swn_quickarchitecture" VALUES (506, 'Monumental arches');
INSERT INTO "swn_quickarchitecture" VALUES (507, 'Keyhole arches');
INSERT INTO "swn_quickarchitecture" VALUES (508, 'Inflexed arches');
INSERT INTO "swn_quickarchitecture" VALUES (509, 'Flat arches');
INSERT INTO "swn_quickarchitecture" VALUES (510, 'Corbelled arches');
INSERT INTO "swn_quickarchitecture" VALUES (601, 'Canals and pools');
INSERT INTO "swn_quickarchitecture" VALUES (602, 'Balconies and overlooks');
INSERT INTO "swn_quickarchitecture" VALUES (603, 'Subterranean structures');
INSERT INTO "swn_quickarchitecture" VALUES (604, 'Absence or profusion of windows');
INSERT INTO "swn_quickarchitecture" VALUES (605, 'Walled or enclosed courtyards');
INSERT INTO "swn_quickarchitecture" VALUES (606, 'Open plazas');
INSERT INTO "swn_quickarchitecture" VALUES (607, 'Elevated walkways');
INSERT INTO "swn_quickarchitecture" VALUES (608, 'Monoliths or standing stones');
INSERT INTO "swn_quickarchitecture" VALUES (609, 'Meandering pathways');
INSERT INTO "swn_quickarchitecture" VALUES (610, 'Climbing vegetation');
