INSERT INTO "swn_quickcorpreputation" VALUES (1, 'Reckless with the lives of their employees');
INSERT INTO "swn_quickcorpreputation" VALUES (2, 'Reckless with the lives of their employees');
INSERT INTO "swn_quickcorpreputation" VALUES (3, 'Reckless with the lives of their employees');
INSERT INTO "swn_quickcorpreputation" VALUES (4, 'Reckless with the lives of their employees');
INSERT INTO "swn_quickcorpreputation" VALUES (5, 'Reckless with the lives of their employees');
INSERT INTO "swn_quickcorpreputation" VALUES (6, 'Have a dark secret about their board of directors');
INSERT INTO "swn_quickcorpreputation" VALUES (7, 'Have a dark secret about their board of directors');
INSERT INTO "swn_quickcorpreputation" VALUES (8, 'Have a dark secret about their board of directors');
INSERT INTO "swn_quickcorpreputation" VALUES (9, 'Have a dark secret about their board of directors');
INSERT INTO "swn_quickcorpreputation" VALUES (10, 'Have a dark secret about their board of directors');
INSERT INTO "swn_quickcorpreputation" VALUES (11, 'Notoriously xenophobic towards aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (12, 'Notoriously xenophobic towards aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (13, 'Notoriously xenophobic towards aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (14, 'Notoriously xenophobic towards aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (15, 'Notoriously xenophobic towards aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (16, 'Lost much money to an embezzler who evaded arrest');
INSERT INTO "swn_quickcorpreputation" VALUES (17, 'Lost much money to an embezzler who evaded arrest');
INSERT INTO "swn_quickcorpreputation" VALUES (18, 'Lost much money to an embezzler who evaded arrest');
INSERT INTO "swn_quickcorpreputation" VALUES (19, 'Lost much money to an embezzler who evaded arrest');
INSERT INTO "swn_quickcorpreputation" VALUES (20, 'Lost much money to an embezzler who evaded arrest');
INSERT INTO "swn_quickcorpreputation" VALUES (21, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (22, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (23, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (24, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (25, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (26, 'Reliable and trustworthy goods');
INSERT INTO "swn_quickcorpreputation" VALUES (27, 'Stole a lot of R&D from a rival corporation');
INSERT INTO "swn_quickcorpreputation" VALUES (28, 'Stole a lot of R&D from a rival corporation');
INSERT INTO "swn_quickcorpreputation" VALUES (29, 'Stole a lot of R&D from a rival corporation');
INSERT INTO "swn_quickcorpreputation" VALUES (30, 'Stole a lot of R&D from a rival corporation');
INSERT INTO "swn_quickcorpreputation" VALUES (31, 'Stole a lot of R&D from a rival corporation');
INSERT INTO "swn_quickcorpreputation" VALUES (32, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (33, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (34, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (35, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (36, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (37, 'They have high-level political connections');
INSERT INTO "swn_quickcorpreputation" VALUES (38, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (39, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (40, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (41, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (42, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (43, 'Rumored cover-up of a massive industrial accident');
INSERT INTO "swn_quickcorpreputation" VALUES (44, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (45, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (46, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (47, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (48, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (49, 'Stodgy and very conservative in their business plans');
INSERT INTO "swn_quickcorpreputation" VALUES (50, '');
INSERT INTO "swn_quickcorpreputation" VALUES (51, '');
INSERT INTO "swn_quickcorpreputation" VALUES (52, '');
INSERT INTO "swn_quickcorpreputation" VALUES (53, '');
INSERT INTO "swn_quickcorpreputation" VALUES (54, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (55, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (56, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (57, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (58, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (59, 'The company’s owner is dangerously insane');
INSERT INTO "swn_quickcorpreputation" VALUES (60, 'Rumored ties to a eugenics cult');
INSERT INTO "swn_quickcorpreputation" VALUES (61, 'Rumored ties to a eugenics cult');
INSERT INTO "swn_quickcorpreputation" VALUES (62, 'Rumored ties to a eugenics cult');
INSERT INTO "swn_quickcorpreputation" VALUES (63, 'Rumored ties to a eugenics cult');
INSERT INTO "swn_quickcorpreputation" VALUES (64, 'Rumored ties to a eugenics cult');
INSERT INTO "swn_quickcorpreputation" VALUES (65, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (66, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (67, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (68, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (69, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (70, 'Said to have a cache of pretech equipment');
INSERT INTO "swn_quickcorpreputation" VALUES (71, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (72, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (73, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (74, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (75, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (76, 'Possibly teetering on the edge of bankruptcy');
INSERT INTO "swn_quickcorpreputation" VALUES (77, 'Front for a planetary government’s espionage arm');
INSERT INTO "swn_quickcorpreputation" VALUES (78, 'Front for a planetary government’s espionage arm');
INSERT INTO "swn_quickcorpreputation" VALUES (79, 'Front for a planetary government’s espionage arm');
INSERT INTO "swn_quickcorpreputation" VALUES (80, 'Front for a planetary government’s espionage arm');
INSERT INTO "swn_quickcorpreputation" VALUES (81, 'Front for a planetary government’s espionage arm');
INSERT INTO "swn_quickcorpreputation" VALUES (82, 'Secretly run by a psychic cabal');
INSERT INTO "swn_quickcorpreputation" VALUES (83, 'Secretly run by a psychic cabal');
INSERT INTO "swn_quickcorpreputation" VALUES (84, 'Secretly run by a psychic cabal');
INSERT INTO "swn_quickcorpreputation" VALUES (85, 'Secretly run by a psychic cabal');
INSERT INTO "swn_quickcorpreputation" VALUES (86, 'Secretly run by a psychic cabal');
INSERT INTO "swn_quickcorpreputation" VALUES (87, 'Secretly run by hostile aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (88, 'Secretly run by hostile aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (89, 'Secretly run by hostile aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (90, 'Secretly run by hostile aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (91, 'Secretly run by hostile aliens');
INSERT INTO "swn_quickcorpreputation" VALUES (92, 'Secretly run by an unbraked AI');
INSERT INTO "swn_quickcorpreputation" VALUES (93, 'Secretly run by an unbraked AI');
INSERT INTO "swn_quickcorpreputation" VALUES (94, 'Secretly run by an unbraked AI');
INSERT INTO "swn_quickcorpreputation" VALUES (95, 'Secretly run by an unbraked AI');
INSERT INTO "swn_quickcorpreputation" VALUES (96, 'They''ve turned over a new leaf with the new CEO');
INSERT INTO "swn_quickcorpreputation" VALUES (97, 'They''ve turned over a new leaf with the new CEO');
INSERT INTO "swn_quickcorpreputation" VALUES (98, 'They''ve turned over a new leaf with the new CEO');
INSERT INTO "swn_quickcorpreputation" VALUES (99, 'Deeply entangled with the planetary underworld');
INSERT INTO "swn_quickcorpreputation" VALUES (100, 'Deeply entangled with the planetary underworld');
