INSERT INTO "swn_quickroom" VALUES (1, 'Armory: locked gun cabinets, armor racks');
INSERT INTO "swn_quickroom" VALUES (2, 'Armory: locked gun cabinets, armor racks');
INSERT INTO "swn_quickroom" VALUES (3, 'Art studio: half-finished pieces, tools');
INSERT INTO "swn_quickroom" VALUES (4, 'Art studio: half-finished pieces, tools');
INSERT INTO "swn_quickroom" VALUES (5, 'Balcony: flowers, climbing vines');
INSERT INTO "swn_quickroom" VALUES (6, 'Balcony: flowers, climbing vines');
INSERT INTO "swn_quickroom" VALUES (7, 'Ballroom: musical instruments, decorations');
INSERT INTO "swn_quickroom" VALUES (8, 'Ballroom: musical instruments, decorations');
INSERT INTO "swn_quickroom" VALUES (9, 'Barracks: footlockers, stacked bunks');
INSERT INTO "swn_quickroom" VALUES (10, 'Barracks: footlockers, stacked bunks');
INSERT INTO "swn_quickroom" VALUES (11, 'Bath chamber: large bathing pool, steam rooms');
INSERT INTO "swn_quickroom" VALUES (12, 'Bath chamber: large bathing pool, steam rooms');
INSERT INTO "swn_quickroom" VALUES (13, 'Bedroom: locked cabinets, personal mementos');
INSERT INTO "swn_quickroom" VALUES (14, 'Bedroom: locked cabinets, personal mementos');
INSERT INTO "swn_quickroom" VALUES (15, 'Biotech lab: unfinished experiments, toxins');
INSERT INTO "swn_quickroom" VALUES (16, 'Biotech lab: unfinished experiments, toxins');
INSERT INTO "swn_quickroom" VALUES (17, 'Broadcasting stage: holocams, props');
INSERT INTO "swn_quickroom" VALUES (18, 'Broadcasting stage: holocams, props');
INSERT INTO "swn_quickroom" VALUES (19, 'Cellar: mold, dampness, spiderwebs on shelves');
INSERT INTO "swn_quickroom" VALUES (20, 'Cellar: mold, dampness, spiderwebs on shelves');
INSERT INTO "swn_quickroom" VALUES (21, 'Cold storage: haunches of alien meat');
INSERT INTO "swn_quickroom" VALUES (22, 'Cold storage: haunches of alien meat');
INSERT INTO "swn_quickroom" VALUES (23, 'Computer room: flickering servers, vent fans');
INSERT INTO "swn_quickroom" VALUES (24, 'Computer room: flickering servers, vent fans');
INSERT INTO "swn_quickroom" VALUES (25, 'Council chamber: large table, mapboard, records');
INSERT INTO "swn_quickroom" VALUES (26, 'Council chamber: large table, mapboard, records');
INSERT INTO "swn_quickroom" VALUES (27, 'Crypt: sarcophagi, bones, grave goods');
INSERT INTO "swn_quickroom" VALUES (28, 'Crypt: sarcophagi, bones, grave goods');
INSERT INTO "swn_quickroom" VALUES (29, 'Dining room: long tables, epergnes, portraits');
INSERT INTO "swn_quickroom" VALUES (30, 'Dining room: long tables, epergnes, portraits');
INSERT INTO "swn_quickroom" VALUES (31, 'Dormitory: bunks, dividers, common baths');
INSERT INTO "swn_quickroom" VALUES (32, 'Dormitory: bunks, dividers, common baths');
INSERT INTO "swn_quickroom" VALUES (33, 'Engineering workshop: parts, electricity, scrap');
INSERT INTO "swn_quickroom" VALUES (34, 'Engineering workshop: parts, electricity, scrap');
INSERT INTO "swn_quickroom" VALUES (35, 'Game room: Table games, nets, flashing baubles');
INSERT INTO "swn_quickroom" VALUES (36, 'Game room: Table games, nets, flashing baubles');
INSERT INTO "swn_quickroom" VALUES (37, 'Garden: benches, fountains, exotic foliage');
INSERT INTO "swn_quickroom" VALUES (38, 'Garden: benches, fountains, exotic foliage');
INSERT INTO "swn_quickroom" VALUES (39, 'Great hall: large hearth, tables, raised dais');
INSERT INTO "swn_quickroom" VALUES (40, 'Great hall: large hearth, tables, raised dais');
INSERT INTO "swn_quickroom" VALUES (41, 'Greenhouse: vegetables, irrigation systems, insects');
INSERT INTO "swn_quickroom" VALUES (42, 'Greenhouse: vegetables, irrigation systems, insects');
INSERT INTO "swn_quickroom" VALUES (43, 'Icon room: religious paintings, statues, kneelers');
INSERT INTO "swn_quickroom" VALUES (44, 'Icon room: religious paintings, statues, kneelers');
INSERT INTO "swn_quickroom" VALUES (45, 'Kennel: stink, fur, bones, feeding bowls');
INSERT INTO "swn_quickroom" VALUES (46, 'Kennel: stink, fur, bones, feeding bowls');
INSERT INTO "swn_quickroom" VALUES (47, 'Kitchen: boiling pots, ovens, numerous knives');
INSERT INTO "swn_quickroom" VALUES (48, 'Kitchen: boiling pots, ovens, numerous knives');
INSERT INTO "swn_quickroom" VALUES (49, 'Lavatory: sonic showers, nonhuman facilities');
INSERT INTO "swn_quickroom" VALUES (50, 'Lavatory: sonic showers, nonhuman facilities');
INSERT INTO "swn_quickroom" VALUES (51, 'Lecture hall: podium, seats, holoboard');
INSERT INTO "swn_quickroom" VALUES (52, 'Lecture hall: podium, seats, holoboard');
INSERT INTO "swn_quickroom" VALUES (53, 'Library: scrolls, dataslabs, codices, massive folios');
INSERT INTO "swn_quickroom" VALUES (54, 'Library: scrolls, dataslabs, codices, massive folios');
INSERT INTO "swn_quickroom" VALUES (55, 'Lumber room: spare furniture, dropcloths, dust');
INSERT INTO "swn_quickroom" VALUES (56, 'Lumber room: spare furniture, dropcloths, dust');
INSERT INTO "swn_quickroom" VALUES (57, 'Maintenance closet: mops, cleaning solvents, sinks');
INSERT INTO "swn_quickroom" VALUES (58, 'Maintenance closet: mops, cleaning solvents, sinks');
INSERT INTO "swn_quickroom" VALUES (59, 'Medical clinic: empty sprayhypos, antiseptic smell');
INSERT INTO "swn_quickroom" VALUES (60, 'Medical clinic: empty sprayhypos, antiseptic smell');
INSERT INTO "swn_quickroom" VALUES (61, 'Monitoring center: banks of screens, darkness');
INSERT INTO "swn_quickroom" VALUES (62, 'Monitoring center: banks of screens, darkness');
INSERT INTO "swn_quickroom" VALUES (63, 'Mortuary: embalming tools, canopic jars');
INSERT INTO "swn_quickroom" VALUES (64, 'Mortuary: embalming tools, canopic jars');
INSERT INTO "swn_quickroom" VALUES (65, 'Museum: display cases, plaques, audio explanations');
INSERT INTO "swn_quickroom" VALUES (66, 'Museum: display cases, plaques, audio explanations');
INSERT INTO "swn_quickroom" VALUES (67, 'Nursery: toys, brightly-painted walls, cribs');
INSERT INTO "swn_quickroom" VALUES (68, 'Nursery: toys, brightly-painted walls, cribs');
INSERT INTO "swn_quickroom" VALUES (69, 'Operating theater: overhead lights, tables, scalpels');
INSERT INTO "swn_quickroom" VALUES (70, 'Operating theater: overhead lights, tables, scalpels');
INSERT INTO "swn_quickroom" VALUES (71, 'Pantry: dusty cannisters, sacks of grain');
INSERT INTO "swn_quickroom" VALUES (72, 'Pantry: dusty cannisters, sacks of grain');
INSERT INTO "swn_quickroom" VALUES (73, 'Prayer room: icons, kneelers, washbasins');
INSERT INTO "swn_quickroom" VALUES (74, 'Prayer room: icons, kneelers, washbasins');
INSERT INTO "swn_quickroom" VALUES (75, 'Prison cell: mold, vermin, peeling paint');
INSERT INTO "swn_quickroom" VALUES (76, 'Prison cell: mold, vermin, peeling paint');
INSERT INTO "swn_quickroom" VALUES (77, 'Quarantine room: cot, bedpan, handwritten will');
INSERT INTO "swn_quickroom" VALUES (78, 'Quarantine room: cot, bedpan, handwritten will');
INSERT INTO "swn_quickroom" VALUES (79, 'Solarium: transparent aluminum ceiling, plants');
INSERT INTO "swn_quickroom" VALUES (80, 'Solarium: transparent aluminum ceiling, plants');
INSERT INTO "swn_quickroom" VALUES (81, 'Sparring room: floor mats, practice weapons');
INSERT INTO "swn_quickroom" VALUES (82, 'Sparring room: floor mats, practice weapons');
INSERT INTO "swn_quickroom" VALUES (83, 'Storeroom: crates, bales, cabinets, chests');
INSERT INTO "swn_quickroom" VALUES (84, 'Storeroom: crates, bales, cabinets, chests');
INSERT INTO "swn_quickroom" VALUES (85, 'Theater: costumes, stage, secret machinery');
INSERT INTO "swn_quickroom" VALUES (86, 'Theater: costumes, stage, secret machinery');
INSERT INTO "swn_quickroom" VALUES (87, 'Torture chamber: straps, chemicals, recording gear');
INSERT INTO "swn_quickroom" VALUES (88, 'Torture chamber: straps, chemicals, recording gear');
INSERT INTO "swn_quickroom" VALUES (89, 'Trophy room: xenolife body parts, plaques, chairs');
INSERT INTO "swn_quickroom" VALUES (90, 'Trophy room: xenolife body parts, plaques, chairs');
INSERT INTO "swn_quickroom" VALUES (91, 'Unfinished room: bare wiring, stacked paneling');
INSERT INTO "swn_quickroom" VALUES (92, 'Unfinished room: bare wiring, stacked paneling');
INSERT INTO "swn_quickroom" VALUES (93, 'Vault: Cameras, thick doors, timed locks');
INSERT INTO "swn_quickroom" VALUES (94, 'Vault: Cameras, thick doors, timed locks');
INSERT INTO "swn_quickroom" VALUES (95, 'Vestibule: coat racks, shoe rests, matting');
INSERT INTO "swn_quickroom" VALUES (96, 'Vestibule: coat racks, shoe rests, matting');
INSERT INTO "swn_quickroom" VALUES (97, 'Wardrobe: out-of-date clothing, mirrors, shoes');
INSERT INTO "swn_quickroom" VALUES (98, 'Wardrobe: out-of-date clothing, mirrors, shoes');
INSERT INTO "swn_quickroom" VALUES (99, 'Wellhouse: water filters, tanks, heaters');
INSERT INTO "swn_quickroom" VALUES (100, 'Wellhouse: water filters, tanks, heaters');
