INSERT INTO "swn_worldpopulation" VALUES (2, 'Failed colony', 'Failed colonies are occasionally found dotting the worlds of human space. Some date back to the First Wave of human colonization more than a thousand years ago, while others are more recent efforts that guttered out under the strains of a colony’s birth.
Pirate attacks might have wiped out a young colony, as might a hostile biosphere, alien attack, internal dissension, disease outbreaks, failure of vital colonial equipment, or any one of a hundred other disasters. The ruins of the colony might still have valuable pretech artifacts, however, or colonization deeds authorized by neighboring worlds. A few survivors might even have clung to life in the intervening centuries, maintaining some sort of society in the wreckage of their ancestors’ work.', 'Failed');
INSERT INTO "swn_worldpopulation" VALUES (3, 'Outpost', 'Outposts are rarely composed of more than a few hundred or few thousand colonists at the most. Outposts are either very new colonies that have not have the requisite time to grow or they are uncolonized worlds that just happen to have a naval or corporate base on the surface.
Corporate or military outposts aren’t intended to be completely self- sufficient. While large outposts are often forced to raise their own food supplies, replacement personnel, spare parts, and advanced tech must all be brought in from elsewhere. Such temporary outposts are known to find themselves in sudden distress when a vital supply ship fails to make its drop or when some local threat proves more than the staff can handle.
Colonial outposts tend to be better equipped but with less outside backing. Such natives expect to live and die on the world, and are more inclined to build permanent structures and local improvements. Many are exiles, malcontents, or others incapable of tolerating the world that sent them forth, and it can make for a somewhat explosive mix in a young colony. These pioneers tend to be very friendly towards visiting starships, as they are often dependent upon free traders and tramp merchants to bring them vital supplies or news of the sector.
Some “outposts” are really just the stubborn, persistent survivors of a long-failed colonization attempt. These cultures can survive for centuries, perpetually culled by the dangers of the world until the survivors are little more than one more element of the local ecology.', 'Outpost');
INSERT INTO "swn_worldpopulation" VALUES (4, 'Tens of thousands of inhabitants', 'Tens of thousands of inhabitants are often found on newly-colonized worlds, or those with limited arable land. With such a small population, most settlements tend to be clustered close to one another for mutual support and efficient exploitation of land. The atmosphere can be something like that of a village-dotted countryside, with too few people to support large, specialized cities. The major settlement of the planet is usually built around the spaceport.
Politics on planets with so few people tend to be very personal in nature. Individual leaders can address the entire population of a world at a single meeting, and networks of family, friends, and employees can dominate the local social life. This small population combined with limited outside contact can result in somewhat... unusual societies more strongly influenced by a leader’s personal quirks than a more populous planet might be. Some such worlds can grow decidedly unhealthy in their customs and traditions.', '10K+');
INSERT INTO "swn_worldpopulation" VALUES (5, 'Tens of thousands of inhabitants', 'Tens of thousands of inhabitants are often found on newly-colonized worlds, or those with limited arable land. With such a small population, most settlements tend to be clustered close to one another for mutual support and efficient exploitation of land. The atmosphere can be something like that of a village-dotted countryside, with too few people to support large, specialized cities. The major settlement of the planet is usually built around the spaceport.
Politics on planets with so few people tend to be very personal in nature. Individual leaders can address the entire population of a world at a single meeting, and networks of family, friends, and employees can dominate the local social life. This small population combined with limited outside contact can result in somewhat... unusual societies more strongly influenced by a leader’s personal quirks than a more populous planet might be. Some such worlds can grow decidedly unhealthy in their customs and traditions.', '10K+');
INSERT INTO "swn_worldpopulation" VALUES (6, 'Hundreds of thousands of inhabitants', 'Hundreds of thousands of inhabitants make up the population of most frontier worlds, usually ones with adequate supplies of arable land and surface conditions amenable to a human without a vacc suit or filter mask. This level of population is also usually the most that a world at tech level 4 can support using only artificial hydroponic complexes and sealed agricultural systems, so less hospitable planets rarely have more than this many inhabitants.
At this level of population, city-states and hub settlements start to form, and some political divisions might exist beneath the overall planetary government. Regional variations start to become present as towns and smaller settlements start to assert their own cultural traits. Young colonies rarely have much of a framework for resolving these new tensions, and it’s not uncommon for outsiders to end up as catspaws for varying factions.
This level of population is normally the smallest that can create spike drive-equipped starships. Less populous worlds rarely have the broad range of specialists and workers necessary to build such ships, even if they possess the necessary technical information.', '100K+');
INSERT INTO "swn_worldpopulation" VALUES (7, 'Hundreds of thousands of inhabitants', 'Hundreds of thousands of inhabitants make up the population of most frontier worlds, usually ones with adequate supplies of arable land and surface conditions amenable to a human without a vacc suit or filter mask. This level of population is also usually the most that a world at tech level 4 can support using only artificial hydroponic complexes and sealed agricultural systems, so less hospitable planets rarely have more than this many inhabitants.
At this level of population, city-states and hub settlements start to form, and some political divisions might exist beneath the overall planetary government. Regional variations start to become present as towns and smaller settlements start to assert their own cultural traits. Young colonies rarely have much of a framework for resolving these new tensions, and it’s not uncommon for outsiders to end up as catspaws for varying factions.
This level of population is normally the smallest that can create spike drive-equipped starships. Less populous worlds rarely have the broad range of specialists and workers necessary to build such ships, even if they possess the necessary technical information.', '100K+');
INSERT INTO "swn_worldpopulation" VALUES (8, 'Hundreds of thousands of inhabitants', 'Hundreds of thousands of inhabitants make up the population of most frontier worlds, usually ones with adequate supplies of arable land and surface conditions amenable to a human without a vacc suit or filter mask. This level of population is also usually the most that a world at tech level 4 can support using only artificial hydroponic complexes and sealed agricultural systems, so less hospitable planets rarely have more than this many inhabitants.
At this level of population, city-states and hub settlements start to form, and some political divisions might exist beneath the overall planetary government. Regional variations start to become present as towns and smaller settlements start to assert their own cultural traits. Young colonies rarely have much of a framework for resolving these new tensions, and it’s not uncommon for outsiders to end up as catspaws for varying factions.
This level of population is normally the smallest that can create spike drive-equipped starships. Less populous worlds rarely have the broad range of specialists and workers necessary to build such ships, even if they possess the necessary technical information.', '100K+');
INSERT INTO "swn_worldpopulation" VALUES (9, 'Millions of inhabitants', 'Millions of inhabitants are found on some of the more populous frontier worlds, those planets with an excellent climate and soil for agriculture. These worlds teem with human life compared to most of their neighbors, and if they have sufficient technological expertise to build spike drives, they probably are one of the more powerful planets in the sector. The sheer amount of labor and expertise they can put into their projects dwarfs the capabilities of most other worlds.
Some worlds of this type fail to coalesce under a unified planetary government, however, and turn most of their attention to intra- planetary quarrels between different nations or city-states. Full-scale planetary wars have been known to break out on such worlds, with some being reduced to burnt-out cinders by some maltech weapon or by nuclear attacks against regions stripped of their nuke snuffers.', '1M+');
INSERT INTO "swn_worldpopulation" VALUES (10, 'Millions of inhabitants', 'Millions of inhabitants are found on some of the more populous frontier worlds, those planets with an excellent climate and soil for agriculture. These worlds teem with human life compared to most of their neighbors, and if they have sufficient technological expertise to build spike drives, they probably are one of the more powerful planets in the sector. The sheer amount of labor and expertise they can put into their projects dwarfs the capabilities of most other worlds.
Some worlds of this type fail to coalesce under a unified planetary government, however, and turn most of their attention to intra- planetary quarrels between different nations or city-states. Full-scale planetary wars have been known to break out on such worlds, with some being reduced to burnt-out cinders by some maltech weapon or by nuclear attacks against regions stripped of their nuke snuffers.', '1M+');
INSERT INTO "swn_worldpopulation" VALUES (11, 'Billions of inhabitants', 'Billions of inhabitants on a world is a freak occurrence in most sectors, a circumstance dependent on almost perfect planetary conditions, a First Wave date of colonization, and a very large initial colonial expedition. These worlds have been colonized for almost a thousand years, and have likely gone through substantial cultural development and change since the original founding.
Planets with this many inhabitants tend to come in two main varieties. The more common is that of regional hegemon, leveraging its enormous reserves of labor and scientific personnel to build hundreds or thousands of starships. Some hegemons might even have the transport weight and personnel available to colonize or conquer their less powerful neighbors outright, though most hegemons prefer the safer route of docile client states rather than outright conquests.
Not all such worlds have the necessary resources to build starships, even when the labor is cheap and abundant. These worlds tend to take a different route, becoming balkanized, conflict-torn planets not unlike a mid-20th-century Earth. Resource wars are common and local politics revolve around Byzantine feuds and ancient slights. Technology on such planets tends to be very uneven; it is limited or nonexistent in fields that depend on unavailable resources, but the natives often show remarkable sophistication in making the most of what they have available.', '1B+');
INSERT INTO "swn_worldpopulation" VALUES (12, 'Alien civilization', 'Alien civilizations are even rarer than massively human-populated planets, but they can be found in some sectors. On these worlds, any human presence is either nonexistent or simply a token contingent of traders and diplomats. The actual number of aliens may range from a few tens of thousands to teeming worlds of billions.
Alien civilizations appear to be no more immune to conflict, disaster, and decadence than that of humans, and most alien worlds are isolated planets. Some sectors were known to be dominated by alien empires before the Scream, but most inhabited worlds found by colonial surveyors consisted of indigenous, low-tech sapients who evolved on the world, or else were the decaying remnants of a former empire that had fallen apart into isolated colonial worlds.
This fate of growth, expansion, colonization, and collapse appears to be a very common event in the galaxy. Countless alien ruins and lost deep-space artifacts indicate that cycles of growth and decay have been going on for millennia, and there is little way to tell how many alien empires have swept over what is now human space before dwindling to decaying worlds and then empty ruins.
Aliens on a decaying colony are likely to be too burdened by the weight of history and dissolution to be aggressive, but may retain dangerously sophisticated devices and scientific expertise. Newly- rising native sophonts may be more interested in reaching the stars, and their ships might well share the spacelanes with the starships of humankind.', 'Alien');
