# Generated by Django 2.0.5 on 2018-09-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='book',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='spell',
            name='book',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
