# Generated by Django 2.0.5 on 2018-09-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0003_auto_20180913_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(default='1 Action', max_length=32),
        ),
    ]
