# Generated by Django 2.0.5 on 2018-09-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0006_auto_20180913_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='attack_type',
            field=models.CharField(blank=True, choices=[('', 'None'), ('M', 'Melee'), ('R', 'Ranged')], default='', max_length=1),
        ),
    ]
