# Generated by Django 2.0.5 on 2018-09-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0007_auto_20180914_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='material_material',
            field=models.CharField(blank=True, default='', max_length=516),
        ),
    ]
