# Generated by Django 2.0.5 on 2018-09-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0008_auto_20180914_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(default='1 Action', max_length=128),
        ),
    ]
