# Generated by Django 2.0.5 on 2018-09-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd', '0009_auto_20180914_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
